---
stages:
  - test
  - coverage

default:
  before_script:
    - apt-get update -qy
    - apt-get install -y libtidy-dev
    - ruby -v
    - which ruby
    - gem install bundler --no-document
    - bundle install --jobs $(nproc)  "${FLAGS[@]}"

.tests:
  script:
    - bundle exec rake
  stage: test

test:2.6:
  extends: .tests
  image: 'ruby:2.6'
  script:
    - bundle exec rake

test:2.7:
  extends: .tests
  image: 'ruby:2.7'

test:3.0:
  extends: .tests
  image: 'ruby:3.0'

test:3.1:
  extends: .tests
  image: 'ruby:3.1'

test:jruby:
  extends: .tests
  image: 'jruby:9.4-jre'

coverage:
  image: 'ruby:3.1'
  script:
    - bundle exec rake test
  artifacts:
    paths:
      - coverage/
  stage: coverage
