---
AllCops:
  TargetRubyVersion: 2.6
Naming/FileName:
  Enabled: false
Lint/MissingCopEnableDirective:
  Enabled: false
Lint/InterpolationCheck:
  Enabled: false
Lint/UriEscapeUnescape:
  Enabled: false
