---
dist: bionic
sudo: true
language: ruby
cache: bundler
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://github.com/htacg/tidy-html5/releases/download/5.4.0/tidy-5.4.0-64bit.deb; sudo apt-get remove '^libtidy.*';  sudo dpkg -i tidy-5.4.0-64bit.deb; fi
  - gem install bundler --no-document
rvm:
  - 2.5
  - 2.6
  - 2.7
  - 3.0
  - jruby-9.2.12.0
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
notifications:
  email:
    on_success: change
    on_failure: always
script:
  - bundle exec rake
